#!/usr/bin/env bash
# asgk-server systemd 用户服务管理脚本（从 sgw/scripts/sgw-service.sh 改造）。
#
# 取代 sgw-service.sh：asgk-server 是能力代理服务端，吞噬了 sgw 的全部流量内核
# （限流/熔断/缓存/singleflight），并暴露语义能力接口（POST /v1/<capability>）。
# sgw 已标 DEPRECATED（见 packages/sgw/README.md），新部署一律用 asgk-server。
#
# 与 sgw-service.sh 的差异：
#   - unit 名 asgk-server.service（非 sgw.service）
#   - 服务目录 ~/.local/share/asgk-server（非 ~/.local/share/sgw）
#   - 端口 7701（非 7700，避免与仍在跑的 sgw 冲突，渐进切换）
#   - 二进制 asgk-server（非 sgw-proxy）
#   - 描述「A股能力代理服务端」（非「流量网关」）
set -Eeuo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
UNIT_NAME="asgk-server.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"
SERVICE_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/asgk-server"

SERVER_WORK_DIR="${SERVER_WORK_DIR:-$SERVICE_HOME}"
SERVER_HOST="${SERVER_HOST:-127.0.0.1}"
SERVER_PORT="${SERVER_PORT:-7701}"
SERVER_FP_DIR="${SERVER_FP_DIR:-$SERVER_WORK_DIR/fingerprints}"
SERVER_CACHE_DIR="${SERVER_CACHE_DIR:-$SERVER_WORK_DIR/cache}"
SERVER_STATE_DIR="${SERVER_STATE_DIR:-$SERVER_WORK_DIR/state}"

# 后台模式（无 systemd 时使用）的状态文件
BG_PID_FILE="$SERVICE_HOME/bg.pid"
BG_LOG_FILE="$SERVICE_HOME/server.log"
BG_LOCK_FILE="$SERVICE_HOME/bg.lock"

usage() {
    cat <<'EOF'
Usage: asgk-server-service.sh <command>

Commands:
  install      Install asgk-server + asgk CLI (uv tool), write cli.toml, start server.
               Auto-detects backend: systemd user service (Linux) or background mode.
  start        Start the server (auto-dispatch to systemd or background mode)
  stop         Stop the server
  restart      Restart the server
  status       Show server status
  logs         Tail server logs (background mode: tail bg log; systemd: journalctl)
  uninstall    Remove the unit/uv tool/background process; keep the work directory

Backend selection (auto on install, can override with ASGK_BACKEND env):
  ASGK_BACKEND=systemd   use systemd user service (default when available)
  ASGK_BACKEND=background  use nohup background process (macOS/WSL/containers)

Optional environment variables:
  UV_BIN, SERVER_WORK_DIR
  SERVER_HOST, SERVER_PORT, SERVER_FP_DIR, SERVER_CACHE_DIR, SERVER_STATE_DIR
  ASGK_BACKEND  force backend selection (systemd|background)

After install, two binaries are available in ~/.local/bin/:
  asgk-server   the capability proxy server (this service)
  asgk          the data-fetching CLI (9 categories x subcommands)
                run `asgk --list` to see all commands

Client configuration (how the asgk CLI finds this server, in priority order):
  1. export ASGK_SERVER=http://127.0.0.1:7701   (highest)
  2. ~/.config/asgk/cli.toml                     (auto-generated by install)
  3. packaged default                            (http://127.0.0.1:7701)
EOF
}

die() {
    printf 'asgk-server-service: %s\n' "$*" >&2
    exit 1
}

resolve_uv() {
    if [[ -n "${UV_BIN:-}" ]]; then
        [[ -x "$UV_BIN" ]] || die "UV_BIN is not executable: $UV_BIN"
        return
    fi
    if command -v uv >/dev/null 2>&1; then
        UV_BIN=$(command -v uv)
    elif [[ -x "$HOME/.local/bin/uv" ]]; then
        UV_BIN="$HOME/.local/bin/uv"
    else
        die "uv was not found; install uv or set UV_BIN=/absolute/path/to/uv"
    fi
}

require_systemd_user() {
    [[ "$(uname -s)" == "Linux" ]] ||
        die "systemd user services require Linux; current OS is $(uname -s)"
    command -v systemctl >/dev/null 2>&1 || die "systemctl was not found"
    systemctl --user show-environment >/dev/null 2>&1 ||
        die "the systemd user manager is unavailable for $USER"
}

validate_config() {
    [[ "$SERVER_PORT" =~ ^[0-9]+$ ]] || die "SERVER_PORT must be an integer"
    ((SERVER_PORT >= 1 && SERVER_PORT <= 65535)) ||
        die "SERVER_PORT must be between 1 and 65535"
}

systemd_quote() {
    local value="$1"
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//%/%%}
    printf '"%s"' "$value"
}

systemd_path() {
    local value="$1"
    value=${value//\\/\\x5c}
    value=${value// /\\x20}
    value=${value//$'\t'/\\x09}
    value=${value//$'\n'/\\x0a}
    value=${value//%/%%}
    printf '%s' "$value"
}

write_unit() {
    local server_bin="$1"
    local tmp
    mkdir -p "$UNIT_DIR" "$SERVER_WORK_DIR" "$SERVER_FP_DIR" "$SERVER_CACHE_DIR" "$SERVER_STATE_DIR"
    tmp=$(mktemp "$UNIT_PATH.tmp.XXXXXX")
    {
        printf '%s\n' '[Unit]'
        printf '%s\n' 'Description=A-share capability proxy server'
        printf '%s\n' 'Wants=network-online.target'
        printf '%s\n' 'After=network-online.target'
        printf '\n%s\n' '[Service]'
        printf '%s\n' 'Type=simple'
        printf 'WorkingDirectory=%s\n' "$(systemd_path "$SERVER_WORK_DIR")"
        printf 'ExecStart=%s --host %s --port %s --fp-dir %s --cache-dir %s --state-dir %s\n' \
            "$(systemd_quote "$server_bin")" \
            "$(systemd_quote "$SERVER_HOST")" \
            "$(systemd_quote "$SERVER_PORT")" \
            "$(systemd_quote "$SERVER_FP_DIR")" \
            "$(systemd_quote "$SERVER_CACHE_DIR")" \
            "$(systemd_quote "$SERVER_STATE_DIR")"
        printf '%s\n' 'Environment=PYTHONUNBUFFERED=1'
        printf '%s\n' 'Restart=on-failure'
        printf '%s\n' 'RestartSec=5s'
        printf '%s\n' 'TimeoutStopSec=30s'
        printf '%s\n' 'NoNewPrivileges=yes'
        printf '%s\n' 'PrivateTmp=yes'
        printf '\n%s\n' '[Install]'
        printf '%s\n' 'WantedBy=default.target'
    } >"$tmp"
    chmod 0644 "$tmp"
    mv "$tmp" "$UNIT_PATH"
}

install_service() {
    local tool_bin_dir server_bin cli_bin
    validate_config
    resolve_uv
    [[ "$SERVER_WORK_DIR" == /* ]] || die "SERVER_WORK_DIR must be an absolute path"
    # --no-cache：绕过 uv wheel 缓存。版本号未变时 --force 仍可能复用旧 wheel，
    # 导致改动不生效（实测踩坑）；双保护 = --no-cache + pyproject 版本号 bump。
    "$UV_BIN" tool install --force --no-cache "$PROJECT_DIR"
    tool_bin_dir=$("$UV_BIN" tool dir --bin)
    server_bin="$tool_bin_dir/asgk-server"
    cli_bin="$tool_bin_dir/asgk"
    [[ -x "$server_bin" ]] || die "uv installed asgk-server but binary not found at $server_bin"
    [[ -x "$cli_bin" ]] || die "uv installed asgk-server but asgk CLI binary not found at $cli_bin"

    detect_backend
    write_cli_config
    mkdir -p "$SERVER_WORK_DIR" "$SERVER_FP_DIR" "$SERVER_CACHE_DIR" "$SERVER_STATE_DIR"

    if [[ "$ASGK_BACKEND" == "systemd" ]]; then
        write_unit "$server_bin"
        systemctl --user daemon-reload
        systemctl --user enable "$UNIT_NAME"
        systemctl --user start "$UNIT_NAME"
        printf 'Installed and started %s (systemd backend).\n' "$UNIT_NAME"
    else
        start_bg "$server_bin"
        printf 'Installed and started server (background backend).\n'
    fi
    printf 'Service work directory: %s\n' "$SERVER_WORK_DIR"
    printf 'Backend: %s\n' "$ASGK_BACKEND"
    printf 'Binaries installed:\n  %s   (server)\n  %s   (CLI)\n' "$server_bin" "$cli_bin"
    printf 'CLI config written: %s\n' "$CLI_CONFIG_PATH"
    printf '\nThe asgk CLI auto-finds this server via %s.\n' "$CLI_CONFIG_PATH"
    printf 'Or override per-shell: export ASGK_SERVER=http://%s:%s\n' "$SERVER_HOST" "$SERVER_PORT"
}

# ── 后端检测：systemd 优先，否则 background ──────────────────
detect_backend() {
    if [[ -n "${ASGK_BACKEND:-}" ]]; then
        [[ "$ASGK_BACKEND" == "systemd" || "$ASGK_BACKEND" == "background" ]] ||
            die "ASGK_BACKEND must be 'systemd' or 'background', got: $ASGK_BACKEND"
        return
    fi
    if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1 \
       && systemctl --user show-environment >/dev/null 2>&1; then
        ASGK_BACKEND="systemd"
    else
        ASGK_BACKEND="background"
    fi
}

# ── 后台模式（nohup + 单例锁，无 systemd 时使用）──────────────
#
# 单例保障（防止多开）：
#   1. BG_PID_FILE 记录上次启动的 PID；启动前检查该 PID 是否仍存活。
#   2. flock BG_LOCK_FILE 作为互斥锁，串行化 start-bg（防并发启动竞态）。
#   3. 端口探活：即使 PID 文件丢失，启动前也探测端口是否已被占用。
# 三重保护确保「同一台机器上只有一个 server 实例」。

_bg_pid_alive() {
    # 检查 BG_PID_FILE 里的 PID 是否存活且是 asgk-server 进程
    [[ -f "$BG_PID_FILE" ]] || return 1
    local pid
    pid=$(cat "$BG_PID_FILE" 2>/dev/null) || return 1
    [[ -n "$pid" ]] || return 1
    kill -0 "$pid" 2>/dev/null || return 1
    # 确认是 asgk-server 进程（防 PID 复用）
    local cmdline
    cmdline=$(cat "/proc/$pid/cmdline" 2>/dev/null | tr '\0' ' ') || true
    [[ "$cmdline" == *asgk-server* ]] || return 1
    echo "$pid"
}

_port_in_use() {
    # 探测 SERVER_PORT 是否已被监听（ss/nc/lsof 任一可用）
    if command -v ss >/dev/null 2>&1; then
        ss -ltn 2>/dev/null | grep -q ":${SERVER_PORT}\b"
    elif command -v nc >/dev/null 2>&1; then
        nc -z 127.0.0.1 "$SERVER_PORT" 2>/dev/null
    elif command -v lsof >/dev/null 2>&1; then
        lsof -iTCP:"$SERVER_PORT" -sTCP:LISTEN -P -n 2>/dev/null | grep -q LISTEN
    else
        return 1  # 无探测工具，假设未占用
    fi
}

start_bg() {
    # $1 = server_bin 路径。单例启动（flock 串行化 + PID/端口双重检查）。
    #
    # 单例保障：用 flock 对 BG_LOCK_FILE 加排他锁（非阻塞 -n，拿不到就失败），
    # 保证同一时刻只有一个 start_bg 在执行检查+启动的临界区。锁在 fd 关闭时释放
    # （函数末尾 exec 9>&- 显式关闭）。
    local server_bin="$1"
    mkdir -p "$SERVICE_HOME"
    exec 9>"$BG_LOCK_FILE"
    # -n 非阻塞：拿不到锁说明另一个 start 在进行，直接退出
    if ! flock -n 9; then
        exec 9>&-
        die "无法获取锁 $BG_LOCK_FILE（另一个 install/start 在进行？）"
    fi

    # 1. PID 文件检查（已有运行实例 → 跳过）
    if pid=$(_bg_pid_alive); then
        printf 'asgk-server 已在运行（PID %s），跳过启动。\n' "$pid" >&2
        exec 9>&-
        return 0
    fi
    # 2. 端口检查（PID 文件可能丢失，但端口被占说明已在跑）
    if _port_in_use; then
        printf '端口 %s 已被占用，asgk-server 可能已在运行（无 PID 文件）。\n' "$SERVER_PORT" >&2
        printf '如确认无运行实例：rm %s 后重试。\n' "$BG_PID_FILE" >&2
        exec 9>&-
        return 0
    fi

    # 启动（setsid nohup 脱离终端，stdout/stderr → 日志，9>&- 防止 server 继承锁 fd）
    # 关键：若不关 fd 9，server 子进程会继承锁文件描述符，导致锁永不释放，
    # 后续 start_bg 永远拿不到锁（误报"另一个 start 在进行"）。
    setsid nohup "$server_bin" \
        --host "$SERVER_HOST" --port "$SERVER_PORT" \
        --cache-dir "$SERVER_CACHE_DIR" --state-dir "$SERVER_STATE_DIR" \
        --fp-dir "$SERVER_FP_DIR" \
        >>"$BG_LOG_FILE" 2>&1 9>&- &
    local new_pid=$!
    echo "$new_pid" > "$BG_PID_FILE"
    printf 'asgk-server 后台启动（PID %s），日志 %s\n' "$new_pid" "$BG_LOG_FILE" >&2

    # 轮询探活（最多 15s）
    local i rc=1
    for i in $(seq 1 15); do
        if ! kill -0 "$new_pid" 2>/dev/null; then
            printf 'asgk-server 进程意外退出，日志末尾：\n' >&2
            tail -20 "$BG_LOG_FILE" >&2 || true
            rm -f "$BG_PID_FILE"
            exec 9>&-
            return 1
        fi
        if _port_in_use; then
            printf 'asgk-server 就绪（等待 %ss）\n' "$i" >&2
            rc=0
            break
        fi
        sleep 1
    done
    exec 9>&-  # 释放锁
    if [[ $rc -ne 0 ]]; then
        printf 'asgk-server 15s 内未就绪，查日志：%s\n' "$BG_LOG_FILE" >&2
    fi
    return $rc
}

stop_bg() {
    if pid=$(_bg_pid_alive); then
        kill -TERM "$pid" 2>/dev/null || true
        # 等 graceful 退出（最多 5s）
        local i
        for i in $(seq 1 5); do
            kill -0 "$pid" 2>/dev/null || break
            sleep 1
        done
        kill -0 "$pid" 2>/dev/null && { kill -KILL "$pid" 2>/dev/null || true; }
        printf 'asgk-server 已停止（PID %s）\n' "$pid"
    else
        printf 'asgk-server 未运行（无存活 PID）\n'
    fi
    rm -f "$BG_PID_FILE"
}

status_bg() {
    if pid=$(_bg_pid_alive); then
        printf 'asgk-server 正在运行（PID %s，端口 %s）\n' "$pid" "$SERVER_PORT"
        printf '日志：%s\n' "$BG_LOG_FILE"
        return 0
    else
        printf 'asgk-server 未运行\n'
        return 3
    fi
}

write_cli_config() {
    # 生成 ~/.config/asgk/cli.toml，让 asgk CLI 自动指向本服务端。
    # 已存在则不覆盖（用户可能手动改过）。
    local config_dir config_path
    config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/asgk"
    config_path="$config_dir/cli.toml"
    CLI_CONFIG_PATH="$config_path"
    if [[ -f "$config_path" ]]; then
        return  # 尊重用户已有配置
    fi
    mkdir -p "$config_dir"
    cat > "$config_path" <<EOF
# Auto-generated by asgk-server-service.sh install.
# The asgk CLI reads this to find the server. Edit freely, or override with:
#   export ASGK_SERVER=http://your-host:port
[server]
url = "http://${SERVER_HOST}:${SERVER_PORT}"
EOF
}

uninstall_service() {
    resolve_uv
    detect_backend
    # 停掉运行中的实例（按 backend）
    if [[ "$ASGK_BACKEND" == "systemd" ]] && [[ -f "$UNIT_PATH" ]]; then
        systemctl --user disable --now "$UNIT_NAME" >/dev/null 2>&1 || true
        rm -f "$UNIT_PATH"
        systemctl --user daemon-reload
        systemctl --user reset-failed "$UNIT_NAME" >/dev/null 2>&1 || true
    fi
    # 后台模式：杀进程（即使 backend=systemd，也兜底杀残留后台进程）
    stop_bg 2>/dev/null || true
    if "$UV_BIN" tool list | grep -q '^asgk-server '; then
        "$UV_BIN" tool uninstall asgk-server
    fi
    # 提示用户 CLI 配置残留（不自动删，因用户可能手动改过指向别处）
    local config_path="${XDG_CONFIG_HOME:-$HOME/.config}/asgk/cli.toml"
    if [[ -f "$config_path" ]]; then
        printf 'CLI config remains (may have been hand-edited): %s\n' "$config_path"
        printf 'Remove manually if no longer needed: rm %s\n' "$config_path"
    fi
    printf 'Uninstalled asgk-server + asgk binaries; work directory preserved: %s\n' "$SERVICE_HOME"
}

# ── 统一命令派发（按已安装的 backend 自动路由）─────────────────
_dispatch_backend() {
    # 1. 环境变量强制（最高优先级）
    if [[ -n "${ASGK_BACKEND:-}" ]]; then
        echo "$ASGK_BACKEND"
        return
    fi
    # 2. 有 systemd unit 文件 → systemd；否则看 PID 文件
    if [[ -f "$UNIT_PATH" ]]; then
        echo "systemd"
    elif [[ -f "$BG_PID_FILE" ]]; then
        echo "background"
    else
        detect_backend
        echo "$ASGK_BACKEND"
    fi
}

command_name="${1:-}"
# ── 命令处理函数（包成函数避免 case 内 local 语法错误）─────────
cmd_start() {
    local backend bin
    backend=$(_dispatch_backend)
    if [[ "$backend" == "systemd" ]]; then
        require_systemd_user
        systemctl --user start "$UNIT_NAME"
        systemctl --user is-active "$UNIT_NAME"
    else
        resolve_uv
        bin="$("$UV_BIN" tool dir --bin)/asgk-server"
        start_bg "$bin"
    fi
}

cmd_stop() {
    local backend
    backend=$(_dispatch_backend)
    if [[ "$backend" == "systemd" ]]; then
        require_systemd_user
        systemctl --user stop "$UNIT_NAME"
    else
        stop_bg
    fi
}

cmd_restart() {
    local backend bin
    backend=$(_dispatch_backend)
    if [[ "$backend" == "systemd" ]]; then
        require_systemd_user
        systemctl --user restart "$UNIT_NAME"
        systemctl --user is-active "$UNIT_NAME"
    else
        stop_bg 2>/dev/null || true
        resolve_uv
        bin="$("$UV_BIN" tool dir --bin)/asgk-server"
        start_bg "$bin"
    fi
}

cmd_status() {
    local backend
    backend=$(_dispatch_backend)
    if [[ "$backend" == "systemd" ]]; then
        require_systemd_user
        systemctl --user status "$UNIT_NAME" --no-pager
    else
        status_bg
    fi
}

cmd_logs() {
    local backend
    backend=$(_dispatch_backend)
    if [[ "$backend" == "systemd" ]]; then
        require_systemd_user
        journalctl --user-unit "$UNIT_NAME" -f --no-pager
    else
        tail -f "$BG_LOG_FILE"
    fi
}

command_name="${1:-}"
case "$command_name" in
    -h|--help|help)
        usage
        ;;
    install)
        install_service
        ;;
    start|run)
        cmd_start
        ;;
    stop)
        cmd_stop
        ;;
    restart)
        cmd_restart
        ;;
    status)
        cmd_status
        ;;
    logs)
        cmd_logs
        ;;
    uninstall)
        uninstall_service
        ;;
    *)
        usage >&2
        exit 2
        ;;
esac
